name: training
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0
  shorebird_code_push: ^2.0.0
  restart_app: ^1.0.0

  # --- OpenStreetMap Packages ---
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.3.2

  # --- Caching & Network for Maps ---
  flutter_map_cache: ^1.4.0
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  path_provider: ^2.1.2

  # --- Location Services (NEW) ---
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0

  # --- Google Sheets Integration ---
  http: ^1.2.0                             
  shared_preferences: ^2.2.2 

  # --- UI Icons ---
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # --- Icon Generator ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/lcp_data.json
    - assets/credentials.json
    - shorebird.yaml

# --- Icon Configuration ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # Recommended for modern Android