name: training
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # --- OpenStreetMap Packages ---
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.3.2

  # --- Caching & Network for Maps ---
  flutter_map_cache: ^1.4.0
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3  # <--- NEW: For saving map tiles to disk
  path_provider: ^2.1.2                     # <--- NEW: To find where to save files

  # --- Google Sheets Integration ---
  http: ^1.2.0               
  csv: ^6.0.0                
  shared_preferences: ^2.2.2 

  # --- UI Icons ---
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lcp_data.json